// Powers colors.html: streams color data from /colors/<category>.json files
// generated by generate_colors.py, instead of holding everything in memory
// up front. Data is fetched lazily (only the active category / search scope)
// and rendered in small batches as the user scrolls.

const ARCHIVE_CATEGORIES = [
  "Neutrals",
  "Red",
  "Orange",
  "Yellow",
  "Green",
  "Cyan",
  "Blue",
  "Purple",
  "Pink",
  "Pastel",
  "Cyberpunk",
];
const DATA_DIR = "colors";
const BATCH_SIZE = 60;

const grid = document.getElementById("color-grid");
const countEl = document.getElementById("color-count");
const tabs = Array.from(document.querySelectorAll("[data-color-tabs] .tab"));
const searchInput = document.getElementById("color-search");

const cache = new Map(); // category -> array of {name, hex, category}
let activeCategory = "All";
let searchQuery = "";
let filteredList = [];
let renderedCount = 0;
let requestToken = 0;
let sentinelObserver = null;
let searchDebounce = null;

function fileFor(category) {
  return `${DATA_DIR}/${category.toLowerCase()}.json`;
}

async function fetchCategory(category) {
  if (cache.has(category)) return cache.get(category);
  const res = await fetch(fileFor(category));
  if (!res.ok) throw new Error(`Could not load ${category} (${res.status})`);
  const data = await res.json();
  cache.set(category, data);
  return data;
}

async function loadSource(category) {
  if (category === "All") {
    const lists = await Promise.all(
      ARCHIVE_CATEGORIES.map((c) => fetchCategory(c))
    );
    return lists.flat();
  }
  return fetchCategory(category);
}

function applySearch(list) {
  if (!searchQuery) return list;
  const q = searchQuery.toLowerCase().replace(/^#/, "");
  return list.filter(
    (color) =>
      color.name.toLowerCase().includes(q) ||
      color.hex.toLowerCase().replace("#", "").includes(q)
  );
}

function copyHex(hex, chip) {
  const done = () => {
    chip.classList.add("is-copied");
    const label = chip.querySelector("span");
    const original = label.textContent;
    label.textContent = "Copied!";
    setTimeout(() => {
      chip.classList.remove("is-copied");
      label.textContent = original;
    }, 900);
  };
  if (navigator.clipboard && navigator.clipboard.writeText) {
    navigator.clipboard.writeText(hex).then(done).catch(done);
  } else {
    done();
  }
}

function chipEl(color) {
  const div = document.createElement("div");
  div.className = "chip";
  div.style.setProperty("--c", color.hex);
  div.dataset.hex = color.hex;
  div.setAttribute("role", "button");
  div.setAttribute("tabindex", "0");
  div.setAttribute("aria-label", `Copy ${color.name} ${color.hex}`);
  div.innerHTML = `<span>${color.name} · ${color.hex}</span>`;
  div.addEventListener("click", () => copyHex(color.hex, div));
  div.addEventListener("keydown", (event) => {
    if (event.key === "Enter" || event.key === " ") {
      event.preventDefault();
      copyHex(color.hex, div);
    }
  });
  return div;
}

function showLoading(message) {
  grid.innerHTML = "";
  const wrap = document.createElement("div");
  wrap.className = "grid-loading";
  wrap.innerHTML = `<span class="spinner" aria-hidden="true"></span><span>${message}</span>`;
  grid.appendChild(wrap);
}

function showEmpty() {
  grid.innerHTML = `<p class="empty-state">No colors match “${searchQuery}”. Try a different name or hex.</p>`;
}

function showError() {
  grid.innerHTML = `<p class="empty-state">Couldn't load this color set. Please try again.</p>`;
}

function updateCount() {
  if (!countEl) return;
  countEl.textContent = `Showing ${renderedCount.toLocaleString()} of ${filteredList.length.toLocaleString()} colors`;
}

function removeSentinel() {
  const sentinel = document.getElementById("color-grid-sentinel");
  if (sentinel) sentinel.remove();
  if (sentinelObserver) {
    sentinelObserver.disconnect();
    sentinelObserver = null;
  }
}

function ensureSentinel() {
  removeSentinel();
  if (renderedCount >= filteredList.length) return;

  const sentinel = document.createElement("div");
  sentinel.id = "color-grid-sentinel";
  sentinel.className = "grid-sentinel";
  sentinel.innerHTML = `<span class="spinner" aria-hidden="true"></span><span>Loading more…</span>`;
  grid.appendChild(sentinel);

  sentinelObserver = new IntersectionObserver(
    (entries) => {
      if (entries[0].isIntersecting) renderNextBatch();
    },
    { rootMargin: "500px" }
  );
  sentinelObserver.observe(sentinel);
}

function renderNextBatch() {
  removeSentinel();
  const slice = filteredList.slice(renderedCount, renderedCount + BATCH_SIZE);
  if (slice.length === 0) return;
  const frag = document.createDocumentFragment();
  slice.forEach((color) => frag.appendChild(chipEl(color)));
  grid.appendChild(frag);
  renderedCount += slice.length;
  updateCount();
  ensureSentinel();
}

async function applyActive() {
  const token = ++requestToken;
  showLoading(
    activeCategory === "All"
      ? "Loading the full archive…"
      : `Loading ${activeCategory}…`
  );
  if (countEl) countEl.textContent = "Loading colors…";

  try {
    const source = await loadSource(activeCategory);
    if (token !== requestToken) return;

    filteredList = applySearch(source);
    renderedCount = 0;
    grid.innerHTML = "";

    if (filteredList.length === 0) {
      showEmpty();
      updateCount();
      return;
    }

    renderNextBatch();
  } catch (err) {
    if (token !== requestToken) return;
    showError();
    if (countEl) countEl.textContent = "Couldn't load colors";
  }
}

tabs.forEach((tab) => {
  tab.addEventListener("click", () => {
    tabs.forEach((t) => t.classList.toggle("is-active", t === tab));
    activeCategory = tab.textContent.trim();
    applyActive();
  });
});

if (searchInput) {
  searchInput.addEventListener("input", (event) => {
    clearTimeout(searchDebounce);
    const value = event.target.value.trim();
    searchDebounce = setTimeout(() => {
      searchQuery = value;
      applyActive();
    }, 200);
  });
}

applyActive();
